# Generated by Django 6.1.1 on 2026-10-07 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_ranksheet_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='student_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Students.student'),
        ),
    ]
