# Generated by Django 6.1.1 on 2026-10-07 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_task_student_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='student_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_task', to='Students.student'),
        ),
    ]
